file_format: "1"
id: hillside48
name: Hillside48
type: shield
url: https://github.com/mmccoyd/hillside/
requires: [pro_micro]
features:
  - keys
  - encoder
  - underglow
siblings:
  - hillside48_left
  - hillside48_right